//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_VENTA
    {
        public int ID_DETALLE { get; set; }
        public Nullable<int> ID_VENTA { get; set; }
        public Nullable<int> ID_PRODUCTO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public string PRECIO { get; set; }
    
        public virtual VENTA VENTA { get; set; }
    }
}
