//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFORMACION
    {
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string TITULO { get; set; }
        public string IMG { get; set; }
        public string DESCRIPCION { get; set; }
        public int ESTADO { get; set; }
        public int ID_TIPO_INFO { get; set; }
    
        public virtual TIPO_INFO TIPO_INFO { get; set; }
    }
}
