//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public int ID_PRODUCTO { get; set; }
        public Nullable<int> TIPO_PRODUCTO { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> STOCK { get; set; }
        public Nullable<int> PRECIO { get; set; }
        public string img_producto { get; set; }
        public Nullable<int> ACTIVO { get; set; }
        public string DESCRIPCION_CORTA { get; set; }
    
        public virtual TIPO_PRODUCTO TIPO_PRODUCTO1 { get; set; }
    }
}
