//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public int id { get; set; }
        public string correo { get; set; }
        public string pass { get; set; }
        public Nullable<int> TIPO_USUARIO { get; set; }
    
        public virtual TIPO_USUARIO TIPO_USUARIO1 { get; set; }
    }
}
